services:
  postgres:
    image: postgres:18
    container_name: pulse-postgres
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse
    ports:
      - "5432:5432"
    volumes:
      - pulse_postgres:/var/lib/postgresql

volumes:
  pulse_postgres: